# Generated by Django 3.0.6 on 2021-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0013_auto_20200611_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.TextField(default='This is a default value that I am providing', max_length=400),
            preserve_default=False,
        ),
    ]
